import { Context, Markup } from "telegraf";
import { ParseMode } from "telegraf/typings/core/types/typegram";

const content = {
  "Basic Training": {
    introduction: `*BASIC TRAINING: Ang Unang Hakbang ng Isang Gut Guardian*\n_(Introduction to Gut Health - Fun, Engaging, and Relatable!)_\n\nFor Beginners - Simple, relatable, and fun with engaging examples!`,
    topics: {
      "Ano ang Gut? (What is the Gut?)": `📢 _"Mga Gut Guardians, alam niyo ba na ang tiyan mo ay hindi lang basta panunaw ng pagkain? Ito ang central command ng iyong katawan!"_ - Col. Lacto\n\n• Ang *gut* o bituka ay hindi lang pangtunaw ng pagkain, ito rin ang tahanan ng *trillions of bacteria* na tumutulong sa kalusugan mo.\n• May tinatawag tayong *Gut Microbiome* - ito ang komunidad ng mabubuti at masasamang mikrobyo sa loob ng tiyan.\n• Imagine mo ang gut mo na parang *isang lungsod - Gut City*! May mga mabubuting mamamayan (probiotics) at mga bandido (bad bacteria). Kung walang batas at seguridad, magkakagulo!\n\n📍_Fun Fact_: 70% ng immune system mo ay nasa gut! Kaya kung malakas ang iyong Gut City, mas malakas ang depensa mo sa sakit!`,
      "Ano ang Role ng Probiotics? (What Do Probiotics Do?)": `📢 _"Ang Probiotics ay parang mga sundalo ng Gut City—matapang, disiplinado, at handang lumaban para sa kalusugan mo!"_ - Col. Lacto\n\n• *Probiotics* = Mga mabubuting bacteria na lumalaban sa masasamang bacteria.\n• Gumagawa sila ng mga *natural antibiotics* para puksain ang bad bacteria.\n• Tumutulong sa digestion at sumisipsip ng nutrients sa pagkain.\n• Pinapalakas ang immune system para hindi madaling magkasakit.\n\n📍_Tandaan_: Ang probiotic na walang pagkain ay mahina! Kaya importante rin ang *prebiotics* — ito ang pagkain ng probiotics!`,
      "Bakit Mahalaga ang Prebiotics? (Why Do We Need Prebiotics?)": `📢 _"Huwag pabayaan ang gut soldiers mo, pakainin mo sila ng prebiotics!"_ - Col. Lacto\n\n• *Prebiotics* = Pagkain ng probiotics para manatili silang buhay at malakas sa Gut City!\n• Nakukuha sa mga *gulay, prutas, whole grains, at fiber-rich foods* tulad ng saging, bawang, sibuyas, at oats.\n• Parang gasolina ng probiotics - kung walang prebiotics, nanghihina sila!\n\n📍_Tandaan_: Kung gusto mong lumakas ang probiotics mo, kumain ng maraming prebiotics!`,
      "Masama Ba ang Antibiotics? (Are Antibiotics Bad?)": `📢 _"Kapag sumobra ang antibiotics, pati ang good bacteria mo, nauubos!"_ - Col. Lacto\n\n• Ang antibiotics ay mabisa sa pagpatay ng bad bacteria, pero minsan, *nauubos din ang good bacteria* sa proseso.\n• Parang bomba sa Gut City—walang pinipili! Pati mabubuting mamamayan, nadadamay!\n• Kaya kung kailangan uminom ng antibiotics, sabayan ito ng probiotics para bumalik ang good bacteria.\n\n📍_Tandaan_: Gumamit lang ng antibiotics kung talagang kailangan at may reseta ng doktor!`,
      "Ano ang Signs na Mahina ang Gut Health Mo? (Signs of an Unhealthy Gut)": `📢 _"Huwag balewalain ang senyales! Kung may problema sa Gut City mo, mararamdaman mo 'yan!"_ - Col. Lacto\n\n💡 *Mga Palatandaan ng Problema sa Gut:*\n\n❌ *Madalas kang magka-stomach ache* - bloating, kabag, acid reflux, o diarrhea?\n❌ Madali kang mapagod - parang laging kulang sa energy kahit sapat ang tulog?\n❌ *Madalas kang sipunin o magka-allergy* - mahina ang immune system mo!\n❌ *Laging bad mood o stressed* - gut-brain connection 'yan!\n❌ *Ang dumi mo ay hindi consistent* - minsan sobrang tigas, minsan sobrang malambot? Red flag yan!\n\n✅ *Solusyon:*\n\n• Kumain ng *fiber-rich foods at probiotics*\n• Bawasan ang *processed foods at sugar*\n• Uminom ng maraming *tubig*\n• Iwasan ang stress—pahinga rin, Gut Guardian!\n\n📍_Tandaan_: Kung mahina ang Gut City mo, maaapektuhan ang buong katawan mo!`,
      "Gaano Kahalaga ang Fiber? (Why is Fiber Important?)": `📢 _"Walang fiber, walang matinong traffic sa Gut City!"_ - Col. Lacto\n\n• *Fiber* = "Walis tingting" ng bituka—tumutulong sa paglabas ng toxins at waste sa katawan.\n• May *dalawang klase ng fiber*:\n✅ *Soluble Fiber* - Tumutulong sa *cholesterol at blood sugar* (Ex: oats, apples, carrots)\n✅ *Insoluble Fiber* - Tumutulong sa digestion at regular bowel movement (Ex: whole grains, gulay, nuts)\n\n📍_Tandaan_: Kapag kulang ka sa fiber, puwede kang magka-constipation at masisira ang Gut City traffic mo!`,
      "Totoo Ba ang Food Coma? (Is Food Coma Real?)": `📢 _"Ang tamang pagkain, dapat nagbibigay ng energy, hindi antok!"_ - Col. Lacto\n\n• Nakaranas ka na ba ng *sobrang antok pagkatapos kumain*? Yan ang *food coma* o tinatawag na *postprandial somnolence*!\n• *Dahilan*:\n❌ Mataas sa sugar o carbs ang kinain mo ➝ Biglang taas ng blood sugar ➝ Biglang bagsak!\n❌ Mas maraming dugo ang napupunta sa tiyan para sa digestion, kaya nababawasan sa utak!\n❌ Sobrang daming kinain ➝ overload sa Gut City workers mo!\n\n✅ *Solusyon:*\n\n• Huwag sobrahan ang carbs—dagdagan ang protein at fiber sa pagkain!\n• Dahan-dahan lang sa pagkain, huwag lumamon agad!\n• Maglakad-lakad pagkatapos kumain para tulungan ang digestion.\n\n📍_Tandaan_: Kapag healthy ang gut mo, mas energetic ka dapat, hindi antukin!`,
      "Bakit Tayo Nagbuburp o Nagkakautot? (Why Do We Burp and Fart?)": `📢 _"Walang masama sa pagbuburp at pag-utot—sign yan na gumagana ang Gut City mo!"_ - Col. Lacto\n\n• *Burping (dighay)* = Labis na hangin sa tiyan na lumalabas sa bibig.\n✅ Dahilan: Masyadong mabilis kumain, uminom ng carbonated drinks, o stress!\n• *Farting (utot)* = Normal na proseso ng gut bacteria sa pagtunaw ng pagkain.\n✅ Dahilan: High-fiber foods, fermentation process ng probiotics, o gut imbalance.\n\n❌ *Kailan ito nagiging masama?*\n\n• Kung *sobrang baho* - baka may gut imbalance o food intolerance ka!\n• Kung *madalas at masakit sa tiyan* - baka may leaky gut o IBS (Irritable Bowel Syndrome).\n\n✅ *Solusyon:*\n\n• Dahan-dahan sa pagkain, iwasan ang sobrang carbonated drinks.\n• Kumain ng balanced diet para hindi masyadong gassy ang gut bacteria mo!\n• Mag-exercise para mas mabilis mawala ang sobrang gas sa tiyan.\n\n📍_Tandaan_: Normal ang utot at dighay, pero kung sobra, baka kailangan mo nang ayusin ang Gut City mo!`,
      "Totoo Ba ang Gut Feeling? (Is Gut Feeling Real?)": `📢 _"Kapag may bad gut feeling ka, minsan, totoo 'yan—may koneksyon kasi ang gut at utak mo!"_ - Col. Lacto\n\n• Ang gut at utak mo ay magkadugtong sa pamamagitan ng *Vagus Nerve*.\n• Kapag stressed ka, apektado ang digestion mo (kaya minsan sumasakit ang tiyan pag kinakabahan!).\n• Kapag healthy ang gut mo, mas malinaw ang isip mo at mas maganda ang mood mo.\n\n✅ *Paano Palakasin ang Gut-Brain Connection?*\n\n• Kumain ng *Omega-3 foods* tulad ng isda at nuts.\n• Iwasan ang *junk food at sobrang sugar* - nagpapagulo ng mood at focus!\n• Gumamit ng *probiotics* para bumaba ang stress at anxiety.\n\n📍_Tandaan_: Kung malakas ang gut mo, mas malinaw din ang isip mo!`,
      "Ano ang Tamang Kulay at Hugis ng Dumi? (What Does Your Poop Say About Your Health?)": `📢 _"Ang dumi mo ay report card ng Gut City mo! Hindi ito bastang lumalabas lang!"_ - Col. Lacto\n\n💩 Bristol Stool Chart - Ano ang normal?\n✅ *Type 3-4 (Smooth, soft, sausage-like)* - Normal! Maganda ang Gut City mo!\n❌ *Type 1-2 (Matigas at parang pebbles)* - Constipation, kulang sa fiber at tubig!\n❌ *Type 5-7 (Masyadong malambot o watery)* - Diarrhea o gut imbalance!\n\n📍_Tandaan_: Ang ideal poop ay dapat hindi masyadong matigas o malambot—balance lang!`
    }
  },
  "Intermediate Training": {
    introduction: `*INTERMEDIATE TRAINING: Para sa Mas Malalim na Kaalaman sa Gut Health*\n_(Deeper Understanding, Includes Science & Practical Applications!)_\n\nFor those who want deeper understanding, includes scientific insights but remains engaging! These topics connect scientific insights with real-life applications.`,
    topics: {
      "Leaky Gut Syndrome - Kapag Butas ang Depensa ng Gut Mo!": `📢 _"Ang Gut Barrier mo ang pader ng Gut City! Pag ito'y nasira, delikado!"_ - Col. Lacto\n\n• *Leaky Gut* = Nanghihinang lining ng bituka, kaya nakakalusot ang toxins papunta sa dugo!\n• Mga sanhi: *Processed food, stress, alak, labis na antibiotics, at sugar.*\n• *Sintomas*: Pagod, skin issues (acne, eczema), madalas na pagkakasakit, bloating, at pananakit ng kasu-kasuan.\n*Solusyon*: Kumain ng pagkain na pampalakas ng Gut Barrier tulad ng bone broth, fermented foods, at omega-3!\n\n📍_Tandaan_: Kung gusto mong maging malakas ang Gut City mo, siguraduhin mong buo ang pader nito!`,
      "Ang Koneksyon ng Gut at Utak (Gut-Brain Axis)": `📢 _"Oo, may koneksyon ang gut at utak mo—kaya pag may stomach ache ka, minsan nagkaka-anxiety ka rin!"_ - Col. Lacto\n\n• May linya ng komunikasyon ang gut at utak na tinatawag na *Gut-Brain Axis*.\n• 90% ng *serotonin (happy hormone)* ay ginagawa sa gut!\n• Kapag unhealthy ang gut mo, maaaring maging dahilan ito ng *anxiety, depression, at brain fog*.\n• Para lumakas ang Gut-Brain Connection, kumain ng *probiotic-rich foods* at iwasan ang processed foods!\n\n📍_Fun Fact_: Ang gut ay minsang tinatawag na *"Second Brain"* dahil sa dami ng neurons dito!`,
      "Gut Inflammation - Kapag May Gulo sa Gut City!": `📢 _"Kapag may riot sa Gut City mo, siguradong may problema sa health mo!"_ - Col. Lacto\n\n• Ang *inflammation* ay senyales na may problema sa gut mo.\n• Mga sanhi: *Junk food, stress, alak, sugar, at unhealthy lifestyle*.\n• Sintomas: *Acid reflux, bloating, fatigue, weight gain, allergies, at autoimmune diseases*.\n• Solusyon:\n✅ Kumain ng anti-inflammatory foods tulad ng turmeric, ginger, berries, at leafy greens.\n✅ Umiwas sa inflammation triggers tulad ng processed foods, sugar, at stress!\n\n📍_Tandaan_: Kung may riot sa Gut City mo, siguradong may riot din sa buong katawan mo!`,
      "The Gut-Immune Connection - Bakit 70% ng Immune System Nasa Gut?": `📢 _"Kapag mahina ang Gut City mo, mas madali kang dapuan ng sakit!"_ - Col. Lacto\n\n• 70-80% ng *immune system cells* mo ay nasa bituka!\n• May tinatawag tayong *Peyer's Patches*, isang special immune defense team sa intestines.\n• Ang mabuting bacteria (probiotics) ay tinutulungan ang immune system sa pag-detect ng bad bacteria at viruses.\n\n✅ *Paano Palakasin ang Gut-Immune System?*\n\n• Kumain ng fermented foods (yogurt, kimchi, tempeh, miso).\n• Dagdagan ang *Vitamin C, Zinc, at Probiotics* sa diet mo.\n• Bawasan ang processed food at sugar - mahilig d'yan ang bad bacteria!\n\n📍_Tandaan_: Ang malakas na immune system ay nagsisimula sa malakas na Gut City!`,
      "Gut Dysbiosis - Kapag Naging Sobrang Dami ng Bad Bacteria!": `📢 _"Kapag lumakas ang bad bacteria sa Gut City, gulo ang kasunod!"_ - Col. Lacto\n\n• *Dysbiosis* = Imbalance sa good at bad bacteria sa gut.\n• Sanhi:\n❌ Sobrang fast food at processed food\n❌ Labis na antibiotics\n❌ Stress at kulang sa tulog\n❌ Hindi sapat na probiotics at prebiotics\n\n✅ *Solusyon:*\n\n• Kumain ng diverse, fiber-rich foods para dumami ang good bacteria.\n• Magdagdag ng *polyphenol-rich foods* tulad ng dark chocolate, berries, at green tea.\n• Iwasan ang artificial sweeteners—pinapakain lang nito ang bad bacteria!\n\n📍_Tandaan_: Ang secret weapon laban sa dysbiosis ay *balanced diet at lifestyle*!`,
      "Gut Health and Weight Management - May Kinalaman Ba Ang Gut Sa Pagpapapayat?": `📢 _"Hindi lahat ng chubby ay dahil lang sa diet—minsan, may kinalaman ang gut bacteria mo!"_ - Col. Lacto\n\n• Ang gut microbiome mo ay may *direct effect sa metabolism* at fat storage.\n• May "good bacteria" na tumutulong sa fat-burning at may "bad bacteria" na nagpo-promote ng fat storage!\n• *Firmicutes vs. Bacteroidetes*:\n✅ Mas marami ang Bacteroidetes = Mas madaling mag-burn ng fat\n❌ Mas marami ang Firmicutes = Mas madaling mag-gain ng weight\n\n✅ *Paano Palakasin ang Weight-Friendly Gut Bacteria?*\n\n• Kumain ng *high-fiber & fermented foods* para dumami ang Bacteroidetes.\n• Iwasan ang ultra-processed foods—pinapakain nito ang Firmicutes!\n• Mag-exercise! Ang active lifestyle ay nagpapaganda ng gut microbiome diversity.\n\n📍_Tandaan_: Ang gut bacteria mo ay may kinalaman sa bilis ng metabolism mo!`,
      "Candida Overgrowth - Kapag Ang Gut Mo Ay Nasakop Ng Yeast!": `📢 _"Ang candida ay parang pesteng umuubos ng resources ng Gut City mo!"_ - Col. Lacto\n\n• *Candida* ay isang uri ng yeast (fungus) na normal sa katawan pero kapag dumami, nagiging problema!\n• *Signs ng Candida Overgrowth*:\n❌ Madalas na sugar cravings\n❌ Brain fog o parang lutang ang utak\n❌ Fatigue kahit sapat ang tulog\n❌ White coating sa dila (oral thrush)\n❌ Skin issues tulad ng eczema o fungal infections\n\n✅ *Paano Labanan ang Candida Overgrowth?*\n\n• Bawasan ang *sugar* at refined carbs—favorite food ng candida!\n• Kumain ng *probiotics* para labanan ang overgrowth ng yeast.\n• Umiwas sa labis na antibiotics at steroids na maaaring magpalakas ng candida.\n\n📍_Tandaan_: Ang candida ay lumalakas kapag mahina ang gut health mo!`,
      "Ang Epekto ng Stress sa Gut Health - Kapag Ang Stress Ay Sumakop sa Gut City!": `📢 _"Kapag stressed ka, stressed din ang gut mo—at damay ang buong katawan mo!"_ - Col. Lacto\n\n• Ang stress ay nagpapataas ng *cortisol*, na sumisira sa gut lining!\n• Maaari itong magdulot ng *leaky gut, acid reflux, at irritable bowel syndrome (IBS)*.\n• *Signs ng Stress-Induced Gut Problems*:\n❌ Minsan diarrhea, minsan constipation\n❌ Bloating at stomach pain kapag kinakabahan\n❌ Hindi matunawan kapag may anxiety\n\n✅ *Paano Protektahan ang Gut Kapag Stress Ka?*\n\n• Mag-practice ng *deep breathing, meditation, o yoga* para bumaba ang stress levels.\n• Kumain ng *magnesium-rich foods* (bananas, nuts, spinach) para ma-relax ang muscles ng gut mo.\n• Siguraduhing may sapat kang *sleep* dahil nire-repair nito ang gut lining mo!\n\n📍_Tandaan_: Ang kalmado at healthy na utak = Malusog at masayang Gut City!`,
      "The Power of Postbiotics - Ano Ito at Bakit Ito ang Next Level ng Gut Health?": `📢 _"Kung ang probiotics ang soldiers, ang postbiotics ang weapons na nagbabantay sa Gut City mo!"_ - Col. Lacto\n\n• *Postbiotics* = Byproducts ng probiotics na nagbibigay ng health benefits!\n• Isa sa pinaka-powerful na postbiotic ay *Urolithin A*, na may anti-aging at mitochondrial-boosting properties!\n• *Benefits ng Postbiotics*:\n✅ Anti-inflammatory properties\n✅ Pinapalakas ang immune system\n✅ Tumutulong sa gut barrier repair\n✅ Nakakatulong sa longevity o long life!\n\n✅ *Paano Makakakuha ng Postbiotics?*\n\n• Kumain ng fermented foods tulad ng kimchi, yogurt, at natto.\n• Pumili ng probiotic supplements na may kasamang postbiotics.\n\n📍_Tandaan_: Ang probiotics ay buhay na good bacteria, pero ang *postbiotics ay ang kanilang secret weapon!*`
    }
  },
  "Advanced Training": {
    introduction: `*ADVANCED TRAINING: Para sa Gut Experts at Future Leaders!*\n_(High-Level Science, Deep Insights, and Practical Implementation!)_\n\nFor serious learners, deeper insights with scientific references but still engaging! These topics go deep into science while keeping them engaging and practical.`,
    topics: {
      "The Science of Fermentation - Paano Ginagawa ang Probiotic Foods?": `📢 _"Ang fermentation ay isang sinaunang siyensiya na nagpa-power up sa probiotics!"_ - Col. Lacto\n\n• Fermentation = Natural process kung saan ang *bacteria at yeast* ay tumutulong sa pagbuo ng probiotics.\n• Paano ito gumagana? Ang good bacteria ay kumakain ng sugar sa pagkain at ginagawa itong lactic acid, na nagpaparami ng probiotics!\n• Halimbawa ng fermented foods: *Kimchi, yogurt, sauerkraut, kombucha, at miso*!\n\n📍_Tandaan_: Ang tunay na probiotics ay buhay! Kaya siguraduhing *unpasteurized* ang fermented foods mo para buhay ang good bacteria!`,
      "Gut Health and Longevity - Paano Ka Tatagal?": `📢 _"Kung malakas ang Gut City mo, tatagal ka nang matagal!"_ - Col. Lacto\n\n• Ang healthy gut ay susi sa *anti-aging*!\n• May *longevity bacteria* na tumutulong sa immune system at anti-aging.\n• Ang sikreto ng centenarians? *Fiber-rich diets, fermented foods, at minimal stress*!\n\n📍_Fun Fact_: Ang Gut Health ay konektado sa Blue Zones—mga lugar kung saan maraming taong umaabot ng 100 years old!`,
      "The Gut-Liver Connection - Kapag Barado ang Detox System Mo!": `📢 _"Kung factory ang katawan mo, ang atay ang detox machine—pero kung sira ang Gut City mo, overload ang atay mo!"_ - Col. Lacto\n\n• Ang *gut at liver* ay konektado sa pamamagitan ng *gut-liver axis*.\n• Ang toxins mula sa bituka ay dapat hinaharang ng gut barrier, pero kapag may *leaky gut*, napupunta ang toxins sa atay.\n• Kapag laging bugbog ang liver sa toxins, nahihirapan itong mag-detox at puwedeng mauwi sa *fatty liver disease*!\n\n✅ *Paano Alagaan ang Gut-Liver Connection?*\n\n• Kumain ng *anti-inflammatory foods* tulad ng turmeric, green leafy vegetables, at beets.\n• Bawasan ang *alcohol, processed foods, at sugar* — sila ang nagpapahirap sa liver!\n• Dagdagan ang *fermented foods at fiber* para maiwasan ang leaky gut.\n\n📍_Tandaan_: Kung gusto mong malinis ang katawan mo, ayusin mo muna ang Gut City mo!`,
      "The Gut-Skin Connection - Bakit Ang Healthy Gut ay Equals sa Glowing Skin?": `📢 _"Hindi lahat ng skin problems ay dahil sa skincare—minsan, nasa loob ng katawan ang problema!"_ - Col. Lacto\n\n• Ang *gut health* ay may direct effect sa skin!\n• Kapag may *gut inflammation*, puwedeng magresulta ito sa *acne, eczema, psoriasis, at premature aging*.\n• Ang tinatawag na *Skin Microbiome* ay nagde-depend sa good bacteria mula sa loob ng katawan.\n\n✅ *Paano Magkaroon ng Gut-Healthy, Glowing Skin?*\n\n• Kumain ng *collagen-boosting foods* tulad ng bone broth, citrus fruits, at berries.\n• Iwasan ang *dairy at refined sugar* kung prone ka sa acne—madalas silang trigger!\n• Magdagdag ng *probiotics at fermented foods* sa diet mo para mabawasan ang skin inflammation.\n\n📍_Tandaan_: Ang *glowing skin ay nagsisimula sa loob—mula sa healthy Gut City*!`,
      "The Future of Gut Health - Precision Probiotics & Postbiotics": `📢 _"Hindi na tayo basta-basta umiinom ng probiotics—ngayon, may targeted probiotics na!"_ - Col. Lacto\n\n• *Precision Probiotics* = Special strains na may specific function, tulad ng:\n✅ *Lactobacillus rhamnosus* - para sa gut-brain health at mood improvement\n✅ *Bifidobacterium longum* - para sa gut-immune system at allergy prevention\n✅ *Akkermansia muciniphila* - para sa fat metabolism at obesity prevention\n\n• *Postbiotics & Synbiotics*:\n✅ *Postbiotics* - Byproducts ng probiotics na may direct health benefits (e.g., Urolithin A).\n✅ *Synbiotics* - Combination ng prebiotics + probiotics para sa maximum effect!\n\n📍_Tandaan_: Ang pag-inom ng *tamang probiotics* ay mas mahalaga kaysa basta uminom lang ng kahit anong probiotic!`,
      "The Science of Gut Fasting - Bakit Importante ang Gut Rest?": `📢 _"Ang gut mo ay parang sundalo—kailangan din nitong magpahinga para lumakas!"_ - Col. Lacto\n\n• *Intermittent Fasting (IF)* ay hindi lang pampapayat—ito rin ay powerful tool para sa gut healing!\n• Kapag walang pagkain, gumagana ang *autophagy* — ang self-cleaning process ng katawan para sa damaged cells.\n• Tumutulong ito sa *gut lining repair, microbiome balance, at inflammation reduction*.\n\n✅ *Paano Mag-Fasting for Gut Health?*\n\n• Subukan ang *12:12 fasting* (12 hrs fasting, 12 hrs eating window) bilang simula.\n• Huwag mag-fasting kung may history ka ng *acid reflux* o ulcers—kailangan mo ng gradual adaptation.\n• Hydration is key—uminom ng *lemon water, green tea, o bone broth* para hindi magka-crash!\n\n📍_Tandaan_: Ang *gut fasting* ay isang powerful healing tool kung tama ang pag-execute!`,
      "Gut Health & Longevity - Paano Pumasa sa Centenarian Secret Formula?": `📢 _"Gusto mo bang umabot ng 100 years old? Ayusin mo ang Gut City mo!"_ - Col. Lacto\n\n• Ang *Blue Zones* ay mga lugar kung saan maraming taong umaabot ng 100 years old!\n• Isa sa kanilang *common factor? Malakas na Gut Microbiome*!\n• *Ano ang sikreto nila?*\n✅ *Plant-based, high-fiber diets* na may fermented foods\n✅ *Regular movement at active lifestyle*\n✅ *Low stress at deep social connections*\n\n✅ *Paano Mo Maa-apply ang Blue Zone Diet?*\n\n• Kumain ng *whole foods* at bawasan ang processed junk food.\n• Magdagdag ng *fermented foods* at natural probiotics sa diet mo.\n• Maglaan ng oras sa *pagpapahinga, socializing, at pagkakaroon ng sense of purpose*.\n\n📍_Tandaan_: Ang *healthy gut = longer life*!`,
      "Genetic & Epigenetic Influence on Gut Health - Destiny or Choice?": `📢 _"Hindi lang genes ang nagde-decide ng health mo—kundi lifestyle mo rin!"_ - Col. Lacto\n\n• *Genetics* ay may role sa gut health—pero *hindi ito fixed*!\n• Ang *Epigenetics* ay nagpapakita na kaya mong i-"turn on" o i-"turn off" ang ilang genes depende sa lifestyle mo!\n• Kung may history ng *gut diseases o autoimmune issues* sa pamilya mo, may magagawa ka pa rin para protektahan ang sarili mo!\n\n✅ *Paano Baguhin ang Genetic Destiny Mo?*\n\n• Iwasan ang *gut-damaging habits* tulad ng stress, sugar, at processed foods.\n• Mag-focus sa *gut-friendly foods, sleep, at movement* para "i-activate" ang good genes!\n• Gumamit ng *precision probiotics* na tumutugma sa genetic predisposition mo.\n\n📍_Tandaan_: *Your genes load the gun, but your lifestyle pulls the trigger!*`
    }
  },
  "Gut-Guard Synbiotic+": {
    introduction: `*GUTGUARD SYNBIOTIC+: REAL-WORLD OBSERVATIONS*\n_(Science behind the testimonials & why it works!)_\n\n📢 _"Mga Gut Guardians, hindi ito basta claim lang—ito ay totoong kwento mula sa mga gumamit ng GutGuard SynBIOTIC+! Alamin natin ang agham sa likod ng kanilang recovery!"_ - Col. Lacto\n\n👉 These are real-world observations from users who experienced noticeable health improvements after regularly taking GutGuard SynBIOTIC+. Each case is backed by scientific explanations as to the possible reasons why positive results were observed after using SynBIOTIC+.`,
    topics: {
      "Gut-Related Disorders - Bakit Mabilis ang Pagsaayos ng Tiyan?": `✔ *Amoebiasis & Chronic Loose Bowel Movements*\n\n_Scientific Explanation:_\n• *Probiotics like Lactobacillus & Bifidobacterium* create a competitive environment where bad bacteria (including amoeba and harmful pathogens) struggle to thrive.\n• *Postbiotics (Urolithin A & L-Tryptophan)* help repair damaged gut lining and restore normal digestion.\n\n📍_Real-Life Testimonial:\n"Madalas akong magka-amoebiasis, pero mula nang uminom ako ng GutGuard, bumalik sa normal ang pagdumi ko at hindi na ako madaling nadadale ng impeksyon!"_\n\n✔ *Severe Constipation (5 Days Without Bowel Movement)*\n\n_Scientific Explanation:_\n• *Prebiotics* (fiber food for probiotics) enhance gut motility.\n• *Lactic acid bacteria* stimulate peristalsis (yung natural movement ng bituka para ilabas ang dumi).\n\n📍_Real-Life Testimonial:\n"Hindi ako dumumi nang 5 araw, pero isang dose lang ng GutGuard, gumaan agad ang pakiramdam ko!"_\n\n✔ *IBS & Bloating*\n\n_Scientific Explanation:_\n• *Probiotics regulate gut microbiome balance*, reducing fermentation gases that cause bloating.\n• *Postbiotics strengthen the gut barrier*, preventing food sensitivities that trigger IBS symptoms.\n\n📍_Real-Life Testimonial:\n"Wala nang matinding kabag at parang mas madaling natutunaw ang pagkain ko!"_`,
      "Inflammatory & Autoimmune Conditions - Bakit Bumaba ang Inflammation?": `✔ *Severe Psoriasis (Skin Peeling & Red Face)*\n\n_Scientific Explanation:_\n• *Gut-Skin Axis*: When gut bacteria are imbalanced, toxins escape into the bloodstream, triggering skin inflammation.\n• *Synbiotics reduce systemic inflammation*, allowing skin to heal naturally.\n\n📍_Real-Life Testimonial:\n"Dati, araw-araw akong nangangapal at nagbabalat ang mukha, pero ngayon, malinis at hindi na namumula ang balat ko!"_\n\n✔ *Chronic Pain (Severe Back Pain, Morphine Use)*\n\n_Scientific Explanation:_\n• *Chronic inflammation is linked to gut health!*\n• *L-Tryptophan helps regulate serotonin*, reducing pain sensitivity.\n• *Urolithin A has mitochondrial benefits*, improving muscle recovery.\n\n📍_Real-Life Testimonial:\n"Umiinom ako ng morphine para sa matinding sakit sa likod, pero ngayon, halos hindi ko na kailangan ng gamot!"_\n\n✔ *Allergic Rhinitis & Sinus Issues*\n\n_Scientific Explanation:_\n• *Probiotics regulate immune response*, reducing allergic reactions.\n• *Stronger gut lining = Less histamine reactions.*\n\n📍_Real-Life Testimonial:\n"Dati, araw-araw akong barado ang ilong, pero ngayon, mas maluwag ang paghinga ko!"_\n\n✔ *Asthma & Faster Mucus Clearance*\n\n_Scientific Explanation:_\n• *Gut microbiome helps regulate lung inflammation.*\n• *Probiotics support mucus clearance*, preventing chronic airway inflammation.\n\n📍_Real-Life Testimonial:\n"Mas mabilis akong gumaling mula sa ubo at mas magaan ang pakiramdam ng dibdib ko!"_`,
      "Hormonal & Reproductive Health - Paano Nakatulong ang Gut sa Hormones?": `✔ *Severe Hormonal Imbalance & Absent Menstruation (5 Months Without Period)*\n\n_Scientific Explanation:_\n• *Gut bacteria influence estrogen metabolism.*\n• *Synbiotics restore hormone balance*, allowing normal menstrual cycles.\n\n📍_Real-Life Testimonial:\n"Limang buwan akong walang period, pero nung tinuloy ko ang GutGuard, bumalik siya sa normal!"_\n\n✔ *Increased Testosterone & Libido in Men*\n\n_Scientific Explanation:_\n• *Probiotics improve testosterone production*, reducing inflammation that disrupts male hormones.\n• *Better gut health = Better blood circulation = Better sexual function*\n\n📍_Real-Life Testimonial:\n"Mas energized ako at parang bumalik ang lakas ko sa loob ng dalawang linggo!"_\n\n✔ *Higher Libido & Natural Lubrication in Women*\n\n_Scientific Explanation:_\n• *Improved gut health enhances estrogen metabolism and blood flow to reproductive organs.*\n• *Balanced microbiome leads to better hydration in tissues.*\n\n📍_Real-Life Testimonial:\n"Kahit senior na ako, nagulat ako na parang bumalik ang sigla ko sa katawan!"_`,
      "Sleep & Energy Improvements - Bakit Mas Malalim ang Tulog?": `✔ *Severe Fatigue & Poor Sleep*\n\n_Scientific Explanation:_\n• *L-Tryptophan is a precursor to melatonin (sleep hormone).*\n• *Probiotics help regulate stress, reducing cortisol spikes.*\n\n📍_Real-Life Testimonial:\n"Ang ganda ng tulog ko ngayon! Mas refreshed ako paggising!"_\n\n✔ *Brain Fog & Lack of Focus*\n\n_Scientific Explanation:_\n• *The gut produces 90% of serotonin*, affecting mood and cognitive function.\n• *Urolithin A supports mitochondrial energy production.*\n\n📍_Real-Life Testimonial:\n"Mas mabilis akong makapag-isip at hindi na ako madaling mapagod!"_`,
      "Skin and Hair - Bakit Pumuti, Kumapal, at Kuminis?": `✔ *Dandruff & Scalp Issues*\n\n_Scientific Explanation:_\n• *Gut health affects sebum production and scalp microbiome.*\n• *Less inflammation = healthier scalp & hair follicles*\n\n📍_Real-Life Testimonial:\n"Wala na akong dandruff! Ang kapal pa ng buhok ko ngayon!"_\n\n✔ *Glowing Skin & Healthier Complexion*\n\n_Scientific Explanation:_\n• *Healthy gut bacteria improve skin hydration and reduce acne triggers.*\n• *Better digestion = Better absorption of skin nutrients*\n\n📍_Real-Life Testimonial:\n"Parang may natural glow ang balat ko ngayon, hindi na dull!"_\n\n✔ *Hair Growth & Thicker Hair*\n\n_Scientific Explanation:_\n• *Probiotics improve nutrient absorption, supporting hair growth.*\n• *Less gut inflammation = better scalp health!*\n\n📍_Real-Life Testimonial:\n"May tumutubo nang bagong baby hairs sa noo ko! Hindi ako makapaniwala!"_`,
      "Final Takeaway: Real Users, Life-Changing Results": `🚀 These aren't just general health benefits - these are specific, documented testimonials of major improvements:\n\n✔ *Gut Repair* ➝ Constipation, diarrhea, bloating relief.\n\n✔ *Skin Conditions* ➝ Psoriasis, glowing skin, dandruff control.\n\n✔ *Chronic Pain* ➝ Severe back pain improved, reduced inflammation.\n\n✔ *Hormonal Balance* ➝ Restored menstruation, increased testosterone & libido.\n\n✔ *Brain & Sleep* ➝ Deeper sleep, improved energy, sharper thinking.\n\n✔ *Hair Growth* ➝ Thicker, stronger, healthier hair.`
    }
  }
};

export const lessons = Object.keys(content);
export const queries = Object.assign({}, ...Object.values(content).map((lesson) => lesson.topics));

export default async function (_: Context) {
  return {
    text: "👋 _Welcome, Gut Guardians!_\n\nAlam mo ba na ang tiyan mo ay hindi lang basta pangtunaw ng pagkain? Ang *gut* ay ang pinaka-importanteng sistema sa katawan—hindi lang ito responsible sa digestion, kundi pati sa *immune system, brain function, hormones, at overall health*!\n\nSa *Gut Health 101*, matututunan mo kung paano pangalagaan ang Gut City mo gamit ang *Basic, Intermediate, at Advanced Training Levels*. Ang goal natin? *Maging malakas, masigla, at protektado laban sa sakit*!\n\nKasama sa kurso na ito ay ang *real-world observations* mula sa mga taong gumamit ng GutGuard SynBIOTIC+ at nakaranas ng tunay at makabuluhang pagbabago sa kanilang kalusugan.\n\n📍_Tandaan_: Ang kaalaman ay ang iyong pinakamalakas na sandata laban sa sakit! Kaya tara, magsimula na tayo! 💪",
    parse_mode: "Markdown" as ParseMode,
    ...Markup.keyboard([...lessons.map((lesson) => [lesson]), ["Back to Main Menu"]]).oneTime()
  };
}

export async function lessonSelected(ctx: Context | any) {
  const { message } = ctx;
  const lesson = content[message.text as keyof typeof content];
  return {
    text: "📌 " + lesson.introduction,
    parse_mode: "Markdown" as ParseMode,
    ...Markup.keyboard([...Object.keys(lesson.topics).map((topic) => [topic]), ["Back to Training Levels"]]).resize()
  };
}
