import { Context, Markup } from "telegraf";
import { ParseMode } from "telegraf/typings/core/types/typegram";

export const queries = {
  "Paano Nabubuo ang Gut Microbiome ng Isang Baby?": `_Ang unang araw ng buhay ng isang baby ay unang araw din ng pagbuo ng Gut City niya!_\n\n*Scientific Explanation:*\n\n• Ang *unang bacteria* na natatanggap ng isang baby ay mula sa *birth canal ng ina (vaginal delivery)*.\n• Ang mga sanggol na ipinanganak via *C-section* ay may ibang microbiome composition—karaniwan ay may mas kaunting probiotics sa kanilang Gut City.\n• *Breastfeeding* ang pinakaunang source ng *good bacteria (Bifidobacteria)* na nagpapalakas ng immune system ng isang sanggol.\n\n✅ *Solusyon:*\n\n• *Breastfeeding* is the best way to help build a strong microbiome for babies.\n• Kung C-section delivery, puwedeng gumamit ng *infant probiotics* para matulungan ang gut development.\n\n📍_Tandaan_: Ang unang 3 taon ng buhay ng isang bata ay critical para sa pagbuo ng matibay na Gut City!`,
  "Paano Nagbabago ang Gut Microbiome ng Bata Habang Lumalaki?": `_Mula baby hanggang bata, nagbabago ang Gut City!_\n\n*Scientific Explanation:*\n\n• Kapag nagsimula nang kumain ng solid foods ang bata, unti-unting nag-iiba ang gut bacteria niya.\n• *Diverse diet* (gulay, prutas, whole grains) ang tumutulong sa pag-develop ng mas matibay at diverse microbiome.\n• Ang madalas na *pag-inom ng antibiotics* sa murang edad ay maaaring makasira sa gut bacteria balance.\n\n✅ *Solusyon:*\n\n• Siguraduhing maraming *fiber-rich foods* at fermented foods tulad ng yogurt para sa healthy gut.\n• Limitahan ang unnecessary antibiotics—gumamit lang kung talagang kailangan.\n\n📍_Tandaan_: Ang batang may strong Gut City ay mas protektado laban sa allergies, gut problems, at sakit!`,
  "Ano ang Nangyayari sa Gut Microbiome ng Teenagers?": `_Kapag teen ka na, ang gut microbiome mo ay mas active, pero prone sa damage!_\n\n*Scientific Explanation:*\n\n• Ang *hormonal changes* ay may direktang epekto sa gut microbiome, kaya ang mga teenagers ay prone sa *acne, mood swings, at digestive issues*.\n• Ang stress mula sa *school, exams, at social life* ay maaaring magdulot ng gut inflammation.\n• Madalas din ang exposure sa *junk food at fast food*, na nagpapalakas ng bad bacteria sa Gut City.\n\n✅ *Solusyon:*\n\n• Dagdagan ang *omega-3 foods at fermented foods* para sa gut-brain balance.\n• Bawasan ang junk food at ultra-processed foods na sumisira sa microbiome.\n• Mag-practice ng *stress management techniques* tulad ng exercise at mindfulness.\n\n📍_Tandaan_: Ang teenage years ay critical para sa gut health—ingatan ito para maiwasan ang long-term health problems!`,
  "Ano ang Nangyayari sa Gut Microbiome Kapag Matanda Na?": `_Habang tumatanda, humihina rin ang Gut City kung hindi ito aalagaan!_\n\n*Scientific Explanation:*\n\n• *Pagbaba ng gut diversity*: Ang gut bacteria ay unti-unting bumababa sa dami at diversity habang tumatanda.\n• *Mas mahina ang digestion*: Mas mahina ang acid production sa tiyan, kaya mas mahirap tunawin ang pagkain.\n• *Pagbaba ng immune function*: Dahil ang immune system ay heavily dependent sa gut, mas nagiging prone sa infection ang matatanda.\n\n✅ *Solusyon:*\n\n• Magdagdag ng *probiotics at prebiotics* sa diet para mapanatili ang gut bacteria balance.\n• Kumain ng *anti-inflammatory foods (leafy greens, turmeric, berries)* para maiwasan ang gut inflammation.\n• Panatilihin ang *active lifestyle* para mapanatili ang gut motility.\n\n📍_Tandaan_: Ang healthy aging ay nagsisimula sa malakas na Gut City!`,
  "Paano Nakakaapekto ang Sakit sa Gut Microbiome?": `_Kapag may sakit ka, nagkakaroon ng gulo sa Gut City mo!_\n\n*Scientific Explanation:*\n\n• Kapag may infection o malubhang sakit, madalas ay *nasisira ang gut microbiome balance*.\n• Ang *mga antibiotics at synthetic medications* ay maaaring pumatay ng good bacteria sa Gut City.\n• Ang stress mula sa sakit ay nagpapahina rin ng *gut lining*, na maaaring humantong sa *leaky gut*.\n\n✅ *Solusyon:*\n\n• Mag-replenish ng *probiotics at fermented foods* pagkatapos gumaling.\n• Gumamit ng *prebiotics* para suportahan ang muling paglaki ng good bacteria.\n• Iwasan ang sobrang *processed foods at refined sugar*, na nagpapahina sa gut recovery.\n\n📍_Tandaan_: Ang gut ay mabilis bumangon kung aalagaan ito nang tama!`,
  "Ano ang Dapat Gawin Para Mabilis Makabawi ang Gut Matapos Uminom ng Antibiotics?": `_Kung nag-antibiotics ka, dapat tulungan mong bumawi ang Gut City mo!_\n\n*Scientific Explanation:*\n\n• Ang antibiotics ay pumapatay ng *both good and bad bacteria*, kaya bumabagsak ang gut balance.\n• Kailangan ng gut ng tulong para ma-repopulate ang healthy bacteria.\n\n✅ *Solusyon:*\n\n• *Uminom ng probiotics* (lalo na ang strains na Lactobacillus at Bifidobacterium) para palitan ang nawalang good bacteria.\n• Kumain ng high-fiber foods at prebiotics para mapakain ang bagong probiotics.\n• Maghintay ng *at least 2-3 hours bago uminom ng probiotics matapos ang antibiotics* para hindi agad mapatay ang good bacteria.\n\n📍_Tandaan_: Hindi lang gamot ang kailangan—kailangan mo ring i-rebuild ang Gut City mo!`,
  "Ano ang Nangyayari sa Gut Microbiome Kapag May Matinding Stress?": `_Kapag stressed ka, hindi lang utak mo ang apektado—pati Gut City mo!_\n\n*Scientific Explanation:*\n\n• Ang *chronic stress* ay nagpapataas ng *cortisol*, isang stress hormone na sumisira sa gut lining.\n• *Stress-induced dysbiosis* ay nagdudulot ng bloating, acid reflux, constipation, at IBS.\n• May direct link ang stress sa *leaky gut syndrome*, kung saan tumatagos ang toxins sa bloodstream.\n\n✅ *Solusyon:*\n\n• Mag-practice ng *stress management techniques* tulad ng meditation, deep breathing, at exercise.\n• Kumain ng gut-friendly foods para suportahan ang gut-brain connection.\n• Siguraduhin ang *sapat na tulog*, dahil ito ay critical para sa gut repair.\n\n📍_Tandaan_: Kapag gusto mong alagaan ang mental health mo, dapat ayusin mo rin ang Gut City mo!`,
  "Ano ang Gut Microbiome at Bakit Ito Mahalaga?": `_Ang Gut Microbiome ay parang Gut City—isang buong komunidad ng good at bad bacteria!_\n\n*Scientific Explanation:*\n\n• Ang *gut microbiome* ay isang koleksyon ng *trillions of bacteria, viruses, at fungi* sa loob ng tiyan.\n• Ang balanse ng good at bad bacteria ang nagtatakda kung malakas o mahina ang immune system mo!\n• 70-80% ng immune cells ay nasa gut—kaya kung malakas ang Gut City mo, malakas ang depensa mo laban sa sakit!\n\n📍_Tandaan_: Kung puro fast food at sugar ang kinakain mo, baka puro masasamang elemento ang naghari sa Gut City mo!`,
  "Ano ang Pinaka-Epektibong Paraan Para Palakasin ang Gut Health?": `_Madali lang yan! Sundin ang 3-P Formula—Prebiotics, Probiotics, at Postbiotics!_\n\n✅ *Prebiotics* - Pagkain ng good bacteria (fiber-rich foods, saging, bawang, sibuyas).\n✅ *Probiotics* - Buhay na good bacteria na nagpapalakas ng Gut City (yogurt, kimchi, tempeh).\n✅ *Postbiotics* - Mga byproducts ng probiotics na nagbibigay ng health benefits (Urolithin A, SCFAs).\n\n📍_Tandaan_: Walang prebiotics? Gutom ang probiotics mo! Walang probiotics? Walang postbiotics!`,
  "Bakit Madalas Akong May Bloated Feeling?": `_Uh-oh! Mukhang traffic jam sa Gut City mo!_\n\n*Scientific Explanation:*\n\n• Ang bloating ay madalas dulot ng sobrang fermentation ng gut bacteria, lalo na kung maraming undigested food.\n• *Dysbiosis (imbalance ng gut bacteria)* ay isa ring sanhi—baka kulang ka sa good bacteria kaya sobrang active ang gas-producing microbes!\n\n✅ *Solusyon:*\n\n• Dahan-dahan sa pagkain para hindi ka makalunok ng maraming hangin.\n• Bawasan ang processed food at sugar—paborito ito ng bad bacteria!\n• Dagdagan ang fermented foods at probiotics para bumalik sa balanse ang gut mo.\n\n📍_Tandaan_: Kapag healthy ang Gut City mo, hindi dapat laging bloated!`,
  "Totoo Bang May Gut-Brain Connection?": `_Oo naman! Ang tiyan mo at utak mo ay may VIP hotline!_\n\n*Scientific Explanation:*\n\n• Ang *Gut-Brain Axis* ay isang direct na koneksyon sa pagitan ng *gut at utak* gamit ang *Vagus Nerve*.\n• Ang gut microbiome ang gumagawa ng *90% ng serotonin (happy hormone)* kaya pag-disrupt ang gut mo, pwedeng magdulot ng anxiety, stress, at depression!\n\n✅ *Solusyon:*\n\n• Kumain ng *fermented foods at omega-3 rich foods* para sa brain at gut support!\n• Iwasan ang stress—masisira ang gut lining kapag palagi kang tensyonado!\n\n📍_Tandaan_: Kapag happy ang Gut City mo, mas malinaw ang pag-iisip mo!`,
  "Paano Makakaiwas sa Leaky Gut?": `_Kung Gut City mo ang pader ng isang fortress, ayaw mo itong mabutas!_\n\n*Scientific Explanation:*\n\n• *Leaky Gut Syndrome* ay nangyayari kapag humina ang lining ng bituka at nakalusot ang toxins papunta sa dugo.\n• Mga sanhi:\n❌ Junk food at sugar (nakakasira ng gut lining).\n❌ Stress (nagpapahina ng gut barrier).\n❌ Labis na antibiotics (pinapatay ang good bacteria).\n\n✅ *Solusyon:*\n\n• Kumain ng *bone broth, omega-3, at collagen-rich foods* para sa gut repair!\n• Bawasan ang processed food at dagdagan ang prebiotics at probiotics!\n\n📍_Tandaan_: Malakas na Gut Barrier = Malakas na katawan!`,
  "Totoo Bang Ang Gut Health ay May Kinalaman sa Weight Loss?": `_Oo, Gut Guardians! May tinatawag tayong fat-burning bacteria!_\n\n*Scientific Explanation:*\n\n• May gut bacteria na nagpapabilis ng metabolism *(Bacteroidetes)*, at may gut bacteria na nagpapadali ng fat storage *(Firmicutes)*.\n• Kapag mas marami ang *Bacteroidetes*, mas madali kang mag-burn ng fat!\n\n✅ *Solusyon:*\n\n• Kumain ng high-fiber foods at fermented foods para dumami ang fat-burning bacteria.\n• Iwasan ang artificial sweeteners at junk food—nagpapalaki ito ng Firmicutes bacteria!\n\n📍_Tandaan_: Ang gut health mo ay may direct na epekto sa timbang mo!`,
  "Paano Nakakatulong ang Urolithin A sa Anti-Aging?": `_Ang Urolithin A ay parang energy booster ng Gut City mo!_\n\n*Scientific Explanation:*\n\n• *Urolithin A* ay isang postbiotic na nagpapalakas ng *mitochondria*, ang energy powerhouse ng cells!\n• Pinapabilis nito ang *autophagy* o self-cleaning process ng cells para maiwasan ang aging-related damage.\n\n✅ *Paano Makukuha ang Urolithin A?*\n\n• Kumain ng *pomegranates, walnuts, at fermented foods*.\n• Gumamit ng *probiotic supplements* na may postbiotic support tulad ng *GutGuard SynBIOTIC+*!\n\n📍_Tandaan_: Kung gusto mong magmukhang bata, palakasin ang Gut City mo!`,
  "Bakit Mas Malakas ang GutGuard SynBIOTIC+ Kaysa Regular Probiotics?": `_Hindi lang ito basta probiotics—ito ay SynBIOTIC+!_\n\n*Scientific Explanation:*\n\n• *Regular probiotics* ay good bacteria lang.\n• *Synbiotics* ay kombinasyon ng *Prebiotics + Probiotics* para sa mas matibay na effect.\n• *GutGuard SynBIOTIC+* may *Postbiotics (Urolithin A & L-Tryptophan)* na nagbibigay ng *anti-aging, immune boost, at gut repair*!\n\n📍_Tandaan_: Para sa *maximum gut health*, kailangan mo ng *Pre, Pro, at Postbiotics*!`,
  "Pwede Bang Gumamit ng Probiotics Kahit Nag-aantibiotics Ako?": `_Oo! Pero dapat alam mo ang tamang paraan!_\n\n*Scientific Explanation:*\n\n• Ang antibiotics ay pumapatay ng both *bad & good bacteria*, kaya nasisira ang gut balance.\n• Ang probiotics ay nakakatulong sa *faster gut microbiome recovery*.\n\n✅ *Paano Gamitin?*\n\n• Uminom ng probiotics *2-3 hours AFTER antibiotics* para hindi sila mapatay agad.\n• Ipagpatuloy ang probiotics kahit tapos na ang antibiotics para ma-repopulate ang good bacteria!\n\n📍_Tandaan_: Kung umiinom ka ng antibiotics, siguraduhing may kasamang probiotics para maiwasan ang gut damage!`,
  "Totoo Ba na ang Gut Health ay May Kinalaman sa Mental Health?": `_Gut at utak? Magkakonektado 'yan—parang secret headquarters at field agents!_\n\n*Scientific Explanation:*\n\n• Ang *gut microbiome* ang gumagawa ng *90% ng serotonin* (happy hormone), kaya may direct effect ito sa mood at mental health.\n• Ang *GABA (Gamma-Aminobutyric Acid)*, isang neurotransmitter na nagpapakalma ng utak, ay ginagawa rin ng gut bacteria.\n• Kapag ang gut mo ay puno ng inflammation o bad bacteria, puwedeng magdulot ito ng *anxiety, brain fog, at depression*!\n\n✅ *Solusyon:*\n\n• Kumain ng *fermented foods (yogurt, kimchi, tempeh)* para mapalakas ang happy bacteria sa gut!\n• Iwasan ang sobrang sugar at ultra-processed foods na nagpapalala ng gut-brain imbalance.\n\n📍_Tandaan_: Kung madalas kang may anxiety o stress, baka may kinalaman ang Gut City mo!`,
  "Paano Nakakaapekto ang Gut Health sa Allergies?": `_Kung mahina ang Gut City mo, parang open gate ito para sa allergens!_\n\n*Scientific Explanation:*\n\n• Ang *overactive immune system* na nagdudulot ng allergies ay madalas nagsisimula sa gut!\n• Kapag may *leaky gut*, nakakalusot ang allergens sa bloodstream at pinapagana ang immune response.\n• Ang good bacteria ay tumutulong sa *immune regulation*, kaya mas kontrolado ang allergic reactions.\n\n✅ *Solusyon:*\n\n• Kumain ng *probiotics at fermented foods* para mapanatili ang immune balance.\n• Iwasan ang processed foods at artificial additives na nagpapalala ng inflammation.\n\n📍_Tandaan_: Ang malusog na Gut City ay kayang magbawas ng allergic reactions!`,
  "Totoo Ba na Nakakaapekto ang Gut Health sa Blood Sugar?": `_Oo! Ang gut bacteria mo ay may direktang papel sa blood sugar control!_\n\n*Scientific Explanation:*\n\n• Ang *gut microbiome* ay tumutulong sa pag-breakdown ng pagkain at pagkontrol ng blood sugar spikes.\n• Ang *Akkermansia muciniphila* ay isang specific probiotic na nagpapalakas ng insulin sensitivity.\n• Kapag sobrang dami ng bad bacteria, mas mahina ang blood sugar regulation, kaya mas mataas ang risk ng *diabetes at metabolic syndrome*!\n\n✅ *Solusyon:*\n\n• Kumain ng high-fiber foods tulad ng *avocados, chia seeds, at whole grains*.\n• Umiwas sa refined sugar at artificial sweeteners—nagpapalala ito ng gut dysbiosis!\n\n📍_Tandaan_: Kung gusto mong kontrolin ang blood sugar mo, ayusin muna ang Gut City mo!`,
  "Ano ang Best Gut-Friendly Diet para sa Longevity?": `_Kung gusto mong umabot ng 100 years old, alamin mo ang sikreto ng centenarians!_\n\n*Scientific Explanation:*\n\n• Ang *Blue Zone Diet* (mga lugar kung saan maraming centenarians) ay binubuo ng:\n✅ *High-fiber, plant-based diet* (gulay, prutas, whole grains).\n✅ *Fermented foods* para sa gut microbiome support.\n✅ *Minimal processed foods at refined sugar*.\n• Ang mga taong may malakas na gut microbiome ay mas may *malakas na immune system at anti-aging benefits*!\n\n✅ *Solusyon:*\n\n• Magdagdag ng *kombucha, kefir, miso, at fermented veggies* sa diet mo.\n• Magbawas ng ultra-processed at artificial foods.\n\n📍_Tandaan_: Ang gut health mo ngayon ang magdidikta ng longevity mo sa hinaharap!`,
  "Paano Nakakaapekto ang Gut Health sa Autoimmune Diseases?": `_Ang immune system mo ay nakadepende sa Gut City mo—kung may riot sa loob, madadamay ang buong katawan!_\n\n*Scientific Explanation:*\n\n• Ang *autoimmune diseases (e.g., lupus, rheumatoid arthritis, multiple sclerosis)* ay konektado sa *leaky gut* at chronic inflammation.\n• Kapag nasira ang gut lining, puwedeng mapagkamalan ng immune system ang sarili nitong cells bilang "kalaban," kaya inaatake nito ang sariling katawan.\n\n✅ *Solusyon:*\n\n• Kumain ng *anti-inflammatory foods* tulad ng turmeric, green leafy vegetables, at omega-3.\n• Iwasan ang gluten, dairy, at processed foods na nagpapalala ng gut permeability.\n\n📍_Tandaan_: Ang pagkontrol sa gut inflammation ay isang paraan para maiwasan ang autoimmune flare-ups!`,
  "Totoo Ba na May Kinalaman ang Gut Health sa Sleep Quality?": `_Oo! Kung magulo ang Gut City mo, magulo rin ang body clock mo!_\n\n*Scientific Explanation:*\n\n• Ang gut microbiome ay tumutulong sa *paggawa ng melatonin* (sleep hormone).\n• Kapag ang gut mo ay puno ng bad bacteria, maaaring mag-trigger ito ng *cortisol spikes* na nakakasira sa sleep cycle mo!\n\n✅ *Solusyon:*\n\n• Kumain ng *magnesium-rich foods* tulad ng bananas, almonds, at dark chocolate.\n• Uminom ng fermented drinks tulad ng kefir o kombucha bago matulog para sa gut relaxation.\n\n📍_Tandaan_: Kung gusto mong magkaroon ng mahimbing na tulog, ayusin ang Gut City mo!`,
  "Ano ang Pinakamagandang Timing Para Uminom ng Probiotics?": `_Timing is key! Hindi lang basta inom—dapat tama ang oras!_\n\n*Scientific Explanation:*\n\n• Ang probiotics ay pinakamahusay iniinom *30 minutes bago kumain o kasabay ng pagkain*, para mas mataas ang survival rate ng good bacteria.\n• Mas mainam ding inumin ito *sa umaga* kung kailan mas mababa ang stomach acid.\n\n✅ *Probiotics Timing Guide:*\n\n✔ Best time = *Before breakfast o kasabay ng pagkain*\n\n📍_Tandaan_: Mas maraming probiotics ang makakarating sa Gut City mo kapag tama ang timing ng pag-inom mo!`,
  "Bakit Mas Malakas ang GutGuard SynBIOTIC+ Kumpara sa Regular Probiotics?": `_Hindi ito basta probiotic—ito ay SynBIOTIC+ na may Pre, Pro, at Postbiotics!_\n\n*Scientific Explanation:*\n\n• *Regular probiotics* ay good bacteria lang.\n• *Synbiotics* ay kombinasyon ng *Prebiotics + Probiotics* para sa mas matibay na effect.\n• *GutGuard SynBIOTIC+* may *Postbiotics (Urolithin A & L-Tryptophan)* na nagbibigay ng *anti-aging, immune boost, at gut repair*!\n\n📍_Tandaan_: Para sa *maximum gut health*, kailangan mo ng *Pre, Pro, at Postbiotics*!`
};

export default async function (_: Context) {
  return {
    text: "Mga Gut Guardians, handa na ba kayo sa ultimate gut health Q&A? Ako si Col. Lacto, at ako ang bahala sa pagsagot sa inyong mga tanong—simple, klaro, at siyempre, may kasamang agham! Let's go!",
    parse_mode: "Markdown" as ParseMode,
    ...Markup.keyboard([...Object.keys(queries).map((query) => [query]), ["Back to Main Menu"]]).resize()
  };
}
